Repository profcomff/auth-api, pull requests merged in 2023-03, with the labels that each got.

#49 login fix
  auth_backend/models/db.py
  auth_backend/settings.py
Labels: bug

#51 Вход в приложение через аккаунт Yandex
  auth_backend/auth_plugins/__init__.py
  auth_backend/auth_plugins/lkmsu.py
  auth_backend/auth_plugins/mymsu.py
  auth_backend/auth_plugins/yandex.py
  auth_backend/cli/process.py
  auth_backend/cli/user_group.py
  auth_backend/settings.py
  tests/test_routes/test_groups.py
Labels: enhancement

#63 Query params GET /group
  auth_backend/auth_plugins/email.py
  auth_backend/auth_plugins/google.py
  auth_backend/auth_plugins/lkmsu.py
  auth_backend/auth_plugins/vk.py
  auth_backend/auth_plugins/yandex.py
  auth_backend/models/db.py
  auth_backend/routes/base.py
  auth_backend/routes/exc_handlers.py
  auth_backend/routes/groups.py
  auth_backend/routes/scopes.py
  auth_backend/routes/user.py
  auth_backend/routes/user_groups.py
  auth_backend/routes/user_session.py
  auth_backend/schemas/__init__.py
  auth_backend/schemas/models.py
  auth_backend/schemas/types/__init__.py
  auth_backend/schemas/types/scopes.py
  auth_backend/utils/security.py
  migrations/versions/6c27352ee53b_unique_scopes.py
  migrations/versions/c03c6b509881_rollback_unique_scopes.py
  tests/conftest.py
  tests/test_routes/test_group_scopes.py
  tests/test_routes/test_groups.py
  tests/test_routes/test_login.py
  tests/test_routes/test_user_groups.py
Labels: bug

#75 Fixes #68 #69 #70 #71 #72 #73 #74
  auth_backend/auth_plugins/auth_method.py
  auth_backend/auth_plugins/google.py
  auth_backend/auth_plugins/lkmsu.py
  auth_backend/auth_plugins/telegram.py
  auth_backend/auth_plugins/vk.py
  auth_backend/auth_plugins/yandex.py
  auth_backend/cli/group.py
  auth_backend/cli/process.py
  auth_backend/cli/scope.py
  auth_backend/cli/user.py
  auth_backend/cli/user_group.py
  auth_backend/models/db.py
  auth_backend/routes/groups.py
  auth_backend/routes/scopes.py
  auth_backend/routes/user.py
  auth_backend/routes/user_session.py
  auth_backend/schemas/models.py
  tests/test_routes/test_group_scopes.py
  tests/test_routes/test_login.py
  tests/test_routes/test_scopes.py
  tests/test_routes/test_user_groups.py
Labels: enhancement

#87 Yandex Domain Whitelist/Blacklist
  auth_backend/auth_plugins/google.py
  auth_backend/auth_plugins/mymsu.py
  auth_backend/auth_plugins/yandex.py
Labels: enhancement

#82 Refactoring
  .github/workflows/black.yml
  auth_backend/auth_plugins/auth_method.py
  auth_backend/auth_plugins/email.py
  auth_backend/auth_plugins/github.py
  auth_backend/auth_plugins/google.py
  auth_backend/auth_plugins/lkmsu.py
  auth_backend/auth_plugins/methods_dict.py
  auth_backend/auth_plugins/mymsu.py
  auth_backend/auth_plugins/physics.py
  auth_backend/auth_plugins/telegram.py
  auth_backend/auth_plugins/vk.py
  auth_backend/auth_plugins/yandex.py
  auth_backend/cli/group.py
  auth_backend/cli/scope.py
  auth_backend/cli/user.py
  auth_backend/cli/user_group.py
  auth_backend/models/db.py
  auth_backend/routes/user.py
  auth_backend/routes/user_session.py
  auth_backend/schemas/models.py
  tests/test_routes/test_change_password.py
  tests/test_routes/test_group_scopes.py
Labels: bug, documentation, enhancement

#91 Linting
  .github/workflows/black.yml
  .github/workflows/tests.yml
Labels: enhancement
